### ISSUE TITLE
Texture name problem

### ISSUE THREAD

**Issue by BubbaFrog** [zmv7/minetest-mod-simple_jetpack#1]
bro the mod works nice it's just this little problem that is simple to fix

![Screenshot from 2022-08-31 08-03-12](https://user-images.githubusercontent.com/100529581/187674412-ed1b083e-7c68-4eb8-b73d-fdc042e0c218.png)

also don't get me wrong you'r mods are nice I love the Rocket Launcher Mod

**Comment by zeminori** [comment]
Whoop, I'm using custom 3d_armor preview page and forgot to make preview image for legacy one
![image](https://user-images.githubusercontent.com/72821250/190504505-a8a15857-45b4-4482-baca-d999e2fe951e.png)

Should be fixed in [f62bd0c](https://github.com/zmv7/minetest-mod-simple_jetpack/commit/f62bd0cbd329ed4af368bebc1c8e67b35c4e1eb1)

**Comment by BubbaFrog** [comment]
great job :  )
